name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 pytest-html flake8-html

      - name: Run flake8 (critical errors)
        run: |
          mkdir -p reports
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format=html --htmldir=reports/flake8_critical

      - name: Run flake8 (style check)
        run: |
          flake8 . --count --ignore=E501 --exit-zero --statistics --format=html --htmldir=reports/flake8_style

      - name: Run pytest
        run: |
          pytest --junitxml=reports/pytest_results.xml --html=reports/pytest_report.html --self-contained-html

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports
